spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: reactive_paradigm
      username: root
      password: pwd
      authentication-database: admin

services:
  order-search:
    url: http://order-search-service:8080
  product-info:
    url: http://product-info-service:8080
